README.md
vite.config.js

Main to Prod for the last time 😭 

---

website/vite.config.js

Co-authored-by: Joseph Sharp <jmsharp-utah@users.noreply.github.com>
Co-authored-by: Casey Wardle <chwardle@utah.gov>

Add dot slash to base path

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/package.json
examples/utah-header/create-react-app/package.json
examples/utah-header/vite/package.json
utah-design-system-website/package.json

Increase versions for deploying

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/package.json
examples/utah-header/create-react-app/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

Up versions of libs for publishing

---

.github/workflows/publish-utah-header.yml

Give github ref to publish

---

@utahdts/utah-design-system/react/components/buttons/IconButton.jsx
@utahdts/utah-design-system/react/components/containers/tabs/TabPanel.jsx
@utahdts/utah-design-system/react/propTypesShapes/RefShape.js

Update Ref type

---

firebase.json

Update site headers (cont)

---

firebase.json

Update site headers (.)

---

firebase.json

Update site headers (..)

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/package.json
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/create-react-app/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

Up version to 1.2.1 for release of sprint

---

@utahdts/utah-design-system-header/src/js/enumerations/domConstants.js
@utahdts/utah-design-system-header/src/js/lifecycle/lifecycle.js
@utahdts/utah-design-system-header/src/js/misc/jsDocTypes.js
@utahdts/utah-design-system-header/src/js/renderables/skipLink/SkipLink.js
@utahdts/utah-design-system-header/src/js/renderables/skipLink/html/SkipLink.html
@utahdts/utah-design-system/css/6-components/_components-index.scss
@utahdts/utah-design-system/css/6-components/base-components/navigation/_skip-link.scss
@utahdts/utah-design-system/index.js
@utahdts/utah-design-system/react/components/templates/DocumentationTemplate.jsx
@utahdts/utah-design-system/react/components/templates/MainContent.jsx
utah-design-system-website/src/react/components/websiteContent/HomeLanding.jsx
utah-design-system-website/src/react/components/websiteContent/Page404.jsx
utah-design-system-website/src/react/components/websiteContent/library/components/navigation/skipLink/SkipLinkDocumentation.jsx
utah-design-system-website/src/websiteUtahHeaderSettings.js

Add skip link to header

---

@utahdts/utah-design-system/react/components/table/TableFilters.jsx

Was getting infinite updating because of bogus
useEffect dependency list.

Fix table filters

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system-header/src/js/lifecycle/lifecycle.js
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/create-react-app/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

Keep only one search form at a time

---

@utahdts/utah-design-system-header/vite.config.js

Is this breaking the header?
UDS-1273

Remove header minification

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/css/6-components/base-components/buttons/_button.scss
@utahdts/utah-design-system/css/6-components/base-components/buttons/_icon-button.scss
@utahdts/utah-design-system/css/6-components/base-components/navigation/_vertical-menu.scss
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/create-react-app/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json
utah-design-system-website/src/css/6-components/project-components/_lightbox.scss

- Fix css bugs for Utah Header in WordPress environment
- Fix css z-index for lightbox

Utah header css fixes

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/css/1-settings/_icons.scss
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/create-react-app/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json
utah-design-system-website/src/react/components/websiteContent/resources/IconsDocumentation/Icons/iconsDocumentationIcons.js

- A "trash" icon has been added to the Design System icon font

Add icon to icon set

---

@utahdts/utah-design-system-header/src/@types/jsDocTypes.d.js
@utahdts/utah-design-system-header/src/js/misc/popupFocusHandler.js
@utahdts/utah-design-system-header/src/js/renderables/mainMenu/renderMainMenu.js
@utahdts/utah-design-system/react/propTypesShapes/header/HeaderMenuItemUrlActionShape.js
utah-design-system-website/src/react/components/websiteContent/library/components/navigation/MainMenu/MainMenuSettingsAndCode.jsx

Add ability for a main menu item w/ children to be clickable

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/create-react-app/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

- Table Pagination component that syncs table filtering and sorting
- Global Banners
- Header menu option actionUrl.skipHandleEvent
- Footer option for customizing Privacy and Terms links
- Table overflow horizontal scroll bar

Up version to v1.12.0

---

@utahdts/utah-design-system-header/src/js/renderables/popupMenu/renderPopupMenu.js

Blur menu item after triggering to prevent flicker

---

@utahdts/utah-design-system/css/6-components/base-components/forms/_multi-select-input.scss

Use more explicit start value

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json
utah-design-system-website/src/react/components/websiteContent/resources/WordPressHeaderPlugin.jsx

- Header WordPress Plugin download link

Fix plugin link

---

@utahdts/utah-design-system/react/components/forms/MultiSelect/MultiSelectTagWrapper.jsx
@utahdts/utah-design-system/react/components/forms/MultiSelect/MultiSelectTags.jsx
@utahdts/utah-design-system/react/components/forms/MultiSelect/functions/removeSelectedOption.jsx

Call multi select's onChange on tag removal

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/package.json
@utahdts/utah-design-system/react/contexts/UtahDesignSystemContext/components/AriaLiveMessages.jsx
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

- Aria messages were visible on the screen

Fix aria messages visibility

---

@utahdts/utah-design-system/react/components/forms/MultiSelect/MultiSelect.jsx
@utahdts/utah-design-system/react/components/forms/MultiSelect/MultiSelectComboBox.jsx
utah-design-system-website/src/@types/jsDocTypes.d.js
utah-design-system-website/src/react/components/websiteContent/library/components/forms/ComboBox/ComboBoxExampleRender.jsx
utah-design-system-website/src/react/components/websiteContent/library/components/forms/ComboBox/ComboBoxPropsDocumentation.jsx
utah-design-system-website/src/react/components/websiteContent/library/components/forms/MultiSelect/MultiSelectDocumentation.jsx
utah-design-system-website/src/react/components/websiteContent/library/components/forms/MultiSelect/MultiSelectExampleCodeReact.jsx
utah-design-system-website/src/react/components/websiteContent/library/components/forms/MultiSelect/MultiSelectExampleProps.jsx
utah-design-system-website/src/react/components/websiteContent/library/components/forms/MultiSelect/MultiSelectExampleRender.jsx
utah-design-system-website/src/react/components/websiteContent/library/components/forms/MultiSelect/MultiSelectPropsDocumentation.jsx

Add ability to add custom items to MultiSelect

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/package.json
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

- Fix menus not popping open on a touch device
- Fix overflowing utah header logo
- Fix overflowing utah header text

up version to 1.15.3

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system-header/src/css/media-queries.css
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

- Fix the width of the search box on mobile.
- Fix the accessibility of the search button on mobile.

1.15.5 fixes

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system-header/src/@types/jsDocTypes.d.js
@utahdts/utah-design-system-header/src/js/renderables/search/searchModal.js
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

fix: Prevent infinite looping when tabbing hidden search modal

---

@utahdts/utah-design-system-header/src/js/renderables/search/searchModal.js

fix: Remove search close/loop from tabindex when not shown

---

@utahdts/utah-design-system/react/components/forms/DateInput.jsx

fix: Keep DateInput unclearable when not clearable

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system-header/src/js/settings/settings.js
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

fix: Account for multiple library loads in header's loading setInterval

---

@utahdts/utah-design-system/react/components/forms/ComboBox/internal/ComboBoxTextInput.jsx
@utahdts/utah-design-system/react/components/forms/MultiSelect/MultiSelectTags.jsx
@utahdts/utah-design-system/react/components/forms/RadioButton/context/RadioButtonGroupContextProvider.jsx
utah-design-system-website/src/css/6-components/_components-index.scss
utah-design-system-website/src/css/6-components/project-components/_demo-form.scss
utah-design-system-website/src/react/components/demo/DemoForm.jsx
utah-design-system-website/src/react/components/websiteContent/library/components/forms/Validation/ValidationDocumentation.jsx

A simple form with simple validation showcasing the Design System's form components.
Had to touch up some components for interoperability with FormContext.
UDS-437

feat: Add Demo Form component (wip)

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system-header/src/css/_action-items.scss
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

- Action item menus overflowing the viewport

Fix action item menu overflow

---

@utahdts/utah-design-system/css/6-components/base-components/footer/_footer-agency-information.scss
@utahdts/utah-design-system/css/6-components/base-components/forms/_combo-box-input.scss
@utahdts/utah-design-system/css/6-components/base-components/forms/_file-input.scss
@utahdts/utah-design-system/css/6-components/base-components/forms/_multi-select-input.scss
@utahdts/utah-design-system/css/6-components/base-components/forms/_switch.scss
utah-design-system-website/src/css/6-components/project-components/_color-contrast.scss
utah-design-system-website/src/css/6-components/project-components/_lightbox.scss

Fix SASS deprecation warnings for nested css declarations

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system-header/src/css/_action-items.scss
@utahdts/utah-design-system-header/src/css/_utah-header-wrapper.scss
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

- Utah Header should have a white background color (just not on the main .utah-design-system css class).

Fix background color for utah header

---

@utahdts/utah-design-system/react/components/navigation/VerticalMenu.jsx
utah-design-system-website/src/react/components/routing/Routing.jsx
utah-design-system-website/src/react/components/websiteContent/library/components/navigation/verticalMenu/VerticalMenuDocumentation.jsx

stop using <nav> for vertical menu wrapper, add <nav> back in for the sidebar menu

---

@utahdts/utah-design-system-header/package.json
@utahdts/utah-design-system/package.json
CHANGELOG.md
examples/design-system/vite-react/package.json
examples/typed/typed-utah-header/package.json
examples/utah-header/angular/package.json
examples/utah-header/vite/package.json
package.json
utah-design-system-website/package.json

- Fixed node module exports for files in the /dist/ directory

Fix dist exports

---

@utahdts/utah-design-system/react/components/PROPTYPES.MD
@utahdts/utah-design-system/react/components/containers/tabs/TabGroup.jsx
@utahdts/utah-design-system/react/components/containers/tabs/TabGroupTitle.jsx
@utahdts/utah-design-system/react/components/containers/tabs/TabPanel.jsx
@utahdts/utah-design-system/react/components/forms/CalendarInput/CalendarInput.jsx
@utahdts/utah-design-system/react/components/forms/CharacterCount.jsx
@utahdts/utah-design-system/react/components/forms/DateInput.jsx
@utahdts/utah-design-system/react/components/forms/ErrorMessage.jsx
@utahdts/utah-design-system/react/components/forms/FileInput.jsx
@utahdts/utah-design-system/react/components/navigation/items/MenuItemFlyout.jsx
@utahdts/utah-design-system/react/components/table/TableFilterComboBox.jsx
@utahdts/utah-design-system/react/components/table/TableFilterComboBoxAllOptions.jsx
@utahdts/utah-design-system/react/components/table/TableFilterDate.jsx
@utahdts/utah-design-system/react/components/table/TableFilterDateRange.jsx
@utahdts/utah-design-system/react/components/table/TableFilterDateRangePopup.jsx
@utahdts/utah-design-system/react/components/table/TableFilterSelect.jsx
@utahdts/utah-design-system/react/components/table/TableFilterSelectAllOptions.jsx
@utahdts/utah-design-system/react/components/table/TableFilterTextInput.jsx
@utahdts/utah-design-system/react/contexts/UtahDesignSystemContext/components/BannersGlobal.jsx

The format guidelines are in the `id` entry of the PROPTYPES.MD file.
UDS-1750

fix: Align dynamic ids to the same format
